openapi: '3.0.2'
info:
  title: API Data Backend
  version: '1.0'
servers:
  - url: http://0.0.0.0:8000

paths:
  # Auth
  /auth/login:
    $ref: components/auth.yaml#/components/Login
  /auth/check_token:
    $ref: components/auth.yaml#/components/CheckToken
  /auth/refresh_token:
    $ref: components/auth.yaml#/components/RefreshToken
  /auth/password:
    $ref: components/auth.yaml#/components/ChangePassword

  # User
  /user:
    $ref: components/user.yaml#/components/GetAllOrCreate
  /user/{id}:
    $ref: components/user.yaml#/components/Crud

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    accessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: access token
    refreshToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: refresh token
