openapi: '3.0.2'
info:
  title: API Data Backend
  version: '1.0'
servers:
  - url: http://127.0.0.1:8000

paths:
  /user:
    get:
      tags:
      - User
      responses:
        '200':
          description: Get all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    post:
      tags:
      - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/safe_user"
      responses:
        '200':
          description: Create a new user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /user/{id}:
    parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: string
          format: cuid
    get:
      tags:
        - User
      responses:
        '200':
          description: Get a user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    put:
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/safe_user"
      responses:
        '200':
          description: Update a user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    delete:
      tags:
        - User
      responses:
          '200':
            description: Update a user
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/user"
          '400':
            description: Error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/error"

components:
  schemas:
    safe_user:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    user:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        role:
          type: string
          default: user
          enum:
            - user
            - admin
            - manager
        createdAt:
          type: string
        updatedAt:
          type: string
    error:
      type: object
      properties:
        error:
          type: string
